#!/bin/sh

cp -a git/lava/usr/local/lib/python3.7/site-packages/dashboard_app /usr/local/lib/python3.7/site-packages/
cp -a git/lava/usr/local/lib/python3.7/site-packages/lava_rest_app /usr/local/lib/python3.7/site-packages/
cp -a git/lava/usr/local/lib/python3.7/site-packages/lava_results_app /usr/local/lib/python3.7/site-packages/
cp -a git/lava/usr/local/lib/python3.7/site-packages/lava_scheduler_app /usr/local/lib/python3.7/site-packages/
cp -a git/lava/usr/local/lib/python3.7/site-packages/lava_server /usr/local/lib/python3.7/site-packages/
cp -a git/lava/usr/local/lib/python3.7/site-packages/linaro_django_xmlrpc /usr/local/lib/python3.7/site-packages/

install -D -p -m0644 etc/env.yaml /etc/lava-server/env.yaml
install -D -p -m0644 etc/instance.conf.template /usr/share/lava-server/instance.conf.template
install -D -p -m0644 etc/lava-logs /etc/lava-server/lava-logs
install -D -p -m0644 etc/lava-master /etc/lava-server/lava-master
install -D -p -m0644 etc/lava-publisher.service /usr/share/lava-server/lava-publisher.service
install -D -p -m0644 etc/lava-server-gunicorn /etc/lava-server/lava-server-gunicorn
install -D -p -m0644 etc/lava-server.conf /etc/apache2/sites-available/lava-server.conf
install -D -p -m0644 etc/logrotate.d/django-log /etc/logrotate.d/django-log
install -D -p -m0644 etc/logrotate.d/lava-logs-log /etc/logrotate.d/lava-logs-log
install -D -p -m0644 etc/logrotate.d/lava-master-log /etc/logrotate.d/lava-master-log
install -D -p -m0644 etc/logrotate.d/lava-publisher-log /etc/logrotate.d/lava-publisher-log
install -D -p -m0644 etc/logrotate.d/lava-server-gunicorn-log /etc/logrotate.d/lava-server-gunicorn-log
install -D -p -m0644 etc/settings.conf /etc/lava-server/settings.conf

install -D -p -m0755 git/lava/usr/local/lib/python3.7/site-packages/lava_server/manage.py /usr/bin/lava-server
install -D -p -m0755 share/postinst.py /usr/share/lava-server/postinst.py

install -d -g lavaserver -o lavaserver /etc/lava-server/dispatcher-config && cp -a lava_scheduler_app/tests/device-types /etc/lava-server/dispatcher-config/ && chown -R lavaserver:lavaserver /etc/lava-server/dispatcher-config
install -d -g lavaserver -o lavaserver /etc/lava-server/dispatcher-config/devices
install -d -g lavaserver -o lavaserver /etc/lava-server/dispatcher-config/health-checks
install -d -g lavaserver -o lavaserver /etc/lava-server/dispatcher.d
install -d -g lavaserver -o lavaserver /var/lib/lava-server/default/archive/job-output
install -d -g lavaserver -o lavaserver /var/lib/lava-server/default/media/job-output && chown -R lavaserver:lavaserver /var/lib/lava-server/default
install -d -g lavaserver -o lavaserver /var/lib/lava-server/home
install -d -m2755 -g adm -o lavaserver /var/log/lava-server && touch /var/log/lava-server/django.log && chown lavaserver:adm /var/log/lava-server/django.log
install -d /usr/local/lib/python3.7/site-packages/lava && cp -a git/lava/usr/local/lib/python3.7/site-packages/lava/utils /usr/local/lib/python3.7/site-packages/lava/
install -d /usr/share/doc/lava-server-doc/html/v2 && cp -a doc/v2/_build/html/* /usr/share/doc/lava-server-doc/html/v2/
install -d /usr/share/doc/lava-server-doc/html/v2/examples && cp -a doc/v2/examples/* /usr/share/doc/lava-server-doc/html/v2/examples/
install -d /usr/share/lava-server/static

ln -sf /usr/local/lib/python3.7/site-packages/django/contrib/admin/static/admin /usr/share/lava-server/static/admin
ln -sf /usr/local/lib/python3.7/site-packages/lava_results_app/static/lava_results_app /usr/share/lava-server/static/lava_results_app
ln -sf /usr/local/lib/python3.7/site-packages/lava_scheduler_app/static/lava_scheduler_app /usr/share/lava-server/static/lava_scheduler_app
ln -sf /usr/local/lib/python3.7/site-packages/lava_server/static/lava_server /usr/share/lava-server/static/lava-server
ln -sf /usr/local/lib/python3.7/site-packages/lava_server/static/lava_server /usr/share/lava-server/static/lava_server
ln -sf /usr/local/lib/python3.7/site-packages/rest_framework/static/rest_framework /usr/share/lava-server/static/rest_framework
ln -sf /usr/share/doc/lava-server-doc/html /usr/share/lava-server/static/docs
